ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS "vehicleType" TEXT,
ADD COLUMN IF NOT EXISTS "vehicleBrand" TEXT,
ADD COLUMN IF NOT EXISTS "vehiclePlates" TEXT,
ADD COLUMN IF NOT EXISTS "isVerified" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "cashInHand" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "maxCashLimit" NUMERIC DEFAULT 1000,
ADD COLUMN IF NOT EXISTS "assignedRestaurantId" TEXT,
ADD COLUMN IF NOT EXISTS "isOnline" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "isAvailable" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "isBlockedDueToCash" BOOLEAN DEFAULT false;
