-- Seed Data for Tlapa-Comida Postgres

DELETE FROM public.products;
DELETE FROM public.merchants;

INSERT INTO public.merchants (id, name, description, category, "logoUrl", "bannerUrl", "prepTime", rating, "deliveryFee", "minOrder", status, coordinates, address) 
VALUES ('merchant-1', 'La Terraza', 'Cocina internacional con los mejores ingredientes de la región', 'cat-1', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800', '20-30', 4.8, 25, 100, 'open', '{"lat":17.5512,"lng":-98.5756}'::jsonb, '{"street":"Calle Juárez #10, Centro","colony":"Centro"}');
INSERT INTO public.merchants (id, name, description, category, "logoUrl", "bannerUrl", "prepTime", rating, "deliveryFee", "minOrder", status, coordinates, address) 
VALUES ('merchant-2', 'Burguer King Tlapa', 'Las mejores hamburguesas artesanales de Tlapa', 'cat-2', 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=200', 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800', '25-40', 4.5, 30, 120, 'open', '{"lat":17.5545,"lng":-98.5789}'::jsonb, '{"street":"Av. Morelos #45, San Francisco","colony":"San Francisco"}');
INSERT INTO public.merchants (id, name, description, category, "logoUrl", "bannerUrl", "prepTime", rating, "deliveryFee", "minOrder", status, coordinates, address) 
VALUES ('merchant-3', 'Tacos "El Paisa"', 'Auténticos tacos al pastor y de suadero', 'cat-3', 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=200', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800', '15-25', 4.9, 15, 50, 'open', '{"lat":17.5501,"lng":-98.5742}'::jsonb, '{"street":"Calle Mina #5, Centro","colony":"Centro"}');

INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-1', 'merchant-1', 'Pizza Pepperoni', 'Masa artesanal con pepperoni premium y queso mozzarella', 180, 180, 'Pizzas', 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500', true, '[{"id":"mg-pizza-size-1","name":"Tamaño","required":true,"multiSelect":false,"minSelect":1,"maxSelect":1,"options":[{"id":"opt-sm","name":"Personal","price":0},{"id":"opt-md","name":"Mediana","price":40},{"id":"opt-lg","name":"Grande","price":80}]},{"id":"mg-pizza-ex-1","name":"Extras","required":false,"multiSelect":true,"minSelect":0,"maxSelect":5,"options":[{"id":"extra-1","name":"Doble queso","price":30},{"id":"extra-2","name":"Jalapeños","price":15},{"id":"extra-3","name":"Champiñones","price":25}]}]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-2', 'merchant-1', 'Pizza Hawaiana', 'Piña miel, jamón ahumado y extra queso mozzarella', 165, 165, 'Pizzas', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500', true, '[{"id":"mg-pizza-size-2","name":"Tamaño","required":true,"multiSelect":false,"minSelect":1,"maxSelect":1,"options":[{"id":"opt-sm","name":"Personal","price":0},{"id":"opt-md","name":"Mediana","price":40},{"id":"opt-lg","name":"Grande","price":80}]},{"id":"mg-pizza-ex-2","name":"Extras","required":false,"multiSelect":true,"minSelect":0,"maxSelect":3,"options":[{"id":"extra-1","name":"Doble queso","price":30}]}]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-3', 'merchant-1', 'Pasta Alfredo', 'Fettuccine cremoso con salsa alfredo y parmesano', 155, 155, 'Pastas', 'https://images.unsplash.com/photo-1645112411341-6c4fd023882a?w=500', true, '[]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-4', 'merchant-1', 'Ensalada César', 'Lechuga romana, crutones, parmesano y aderezo césar', 95, 95, 'Ensaladas', 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=500', true, '[{"id":"mg-ensalada-prot","name":"Proteína","required":false,"multiSelect":false,"minSelect":0,"maxSelect":1,"options":[{"id":"extra-4","name":"Pollo grillé","price":40},{"id":"opt-camaron","name":"Camarón","price":55}]}]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-5', 'merchant-1', 'Limonada Natural', 'Limonada fresca con hierbabuena', 35, 35, 'Bebidas', 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=500', true, '[]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-6', 'merchant-2', 'Hamburguesa Clásica', 'Carne angus, lechuga, tomate, cebolla y salsa especial', 120, 120, 'Hamburguesas', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500', true, '[{"id":"mg-term-6","name":"Término de la carne","required":true,"multiSelect":false,"minSelect":1,"maxSelect":1,"options":[{"id":"opt-medio","name":"Medio","price":0},{"id":"opt-3cuartos","name":"Tres cuartos","price":0},{"id":"opt-bien","name":"Bien cocido","price":0}]},{"id":"mg-extras-6","name":"Extras","required":false,"multiSelect":true,"minSelect":0,"maxSelect":5,"options":[{"id":"extra-5","name":"Tocino extra","price":25},{"id":"extra-6","name":"Queso cheddar","price":15},{"id":"opt-doble","name":"Doble carne","price":45}]}]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-7', 'merchant-2', 'Hamburguesa BBQ', 'Doble carne, salsa BBQ, aros de cebolla y queso gouda', 165, 165, 'Hamburguesas', 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500', true, '[{"id":"mg-term-7","name":"Término de la carne","required":true,"multiSelect":false,"minSelect":1,"maxSelect":1,"options":[{"id":"opt-medio","name":"Medio","price":0},{"id":"opt-3cuartos","name":"Tres cuartos","price":0},{"id":"opt-bien","name":"Bien cocido","price":0}]},{"id":"mg-extras-7","name":"Extras","required":false,"multiSelect":true,"minSelect":0,"maxSelect":3,"options":[{"id":"extra-5","name":"Tocino extra","price":25}]}]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-8', 'merchant-2', 'Papas Francesas', 'Crujientes papas con sal y ketchup', 55, 55, 'Acompañamientos', 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500', true, '[]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-9', 'merchant-2', 'Malteada de Chocolate', 'Cremosa malteada de chocolate con crema batida', 65, 65, 'Bebidas', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500', true, '[]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-10', 'merchant-3', 'Tacos al Pastor (5 pzas)', 'Trompo de cerdo marinado, piña, cebolla y cilantro', 85, 85, 'Tacos', 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500', true, '[{"id":"mg-tortilla-10","name":"Tipo de tortilla","required":true,"multiSelect":false,"minSelect":1,"maxSelect":1,"options":[{"id":"opt-maiz","name":"Maíz","price":0},{"id":"opt-harina","name":"Harina","price":5}]},{"id":"mg-salsa-10","name":"Salsa","required":false,"multiSelect":true,"minSelect":0,"maxSelect":3,"options":[{"id":"extra-7","name":"Salsa extra","price":5},{"id":"extra-8","name":"Guacamole","price":20}]}]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-11', 'merchant-3', 'Tacos de Suadero (5 pzas)', 'Suadero jugoso con limón, cebolla y cilantro', 90, 90, 'Tacos', 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=500', true, '[{"id":"mg-tortilla-11","name":"Tipo de tortilla","required":true,"multiSelect":false,"minSelect":1,"maxSelect":1,"options":[{"id":"opt-maiz","name":"Maíz","price":0},{"id":"opt-harina","name":"Harina","price":5}]},{"id":"mg-salsa-11","name":"Salsa","required":false,"multiSelect":true,"minSelect":0,"maxSelect":2,"options":[{"id":"extra-7","name":"Salsa extra","price":5}]}]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-12', 'merchant-3', 'Quesadilla de Queso', 'Tortilla de maíz con queso Oaxaca derretido', 35, 35, 'Antojitos', 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=500', true, '[{"id":"mg-rell-12","name":"Relleno extra","required":false,"multiSelect":false,"minSelect":0,"maxSelect":1,"options":[{"id":"extra-9","name":"Con picadillo","price":15},{"id":"extra-10","name":"Con chicharrón","price":15},{"id":"opt-flor","name":"Con flor de calabaza","price":15}]}]'::jsonb);
INSERT INTO public.products (id, "merchantId", name, description, price, "originalPrice", category, "imageUrl", "isAvailable", modifiers)
VALUES ('item-13', 'merchant-3', 'Agua de Horchata (1L)', 'Refrescante agua de horchata con canela', 30, 30, 'Bebidas', 'https://images.unsplash.com/photo-1544145945-f904253d0c71?w=500', true, '[]'::jsonb);
